CREATE TABLE users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar NOT NULL,
    last_name varchar NOT NULL,
    username varchar NOT NULL,
    email varchar NOT NULL,
    password varchar NOT NULL,
    user_role varchar NOT NULL,
    is_enabled BOOLEAN
)