CREATE TABLE access_tokens (
    token_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token varchar NOT NULL UNIQUE,
    token_type varchar NOT NULL,
    revoked boolean NOT NULL,
    expired boolean NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(user_id)
)