CREATE TABLE verification_tokens (
    token_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token varchar NOT NULL UNIQUE,
    expiration_date varchar NOT NULL,
    user_id BIGINT NOT NULL
)