CREATE TABLE password_reset_tokens (
    reset_token_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reset_token varchar NOT NULL UNIQUE,
    expiration_date varchar NOT NULL,
    user_id BIGINT NOT NULL
)