server:
  port: 3030

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carspots
    username: chkyoslf
    password: pass123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  main:
    web-application-type: servlet